db:
  pvcname: db-pvc
  pvstorage: 1Gi
  dbdeploymentname: db-deployment
  dbreplicas: 1
  dbpodselector: db
  dbcontainername: db
  dbimage:
    repository: mongo
    tag: "latest"
  dbvolumename: db-storage
  dbmountpath: /data/db
  dbservicename: db
backend:
  backendnamespace: backendnamespace
  backendconfigmapname: backendconfigmap
  backendsecretname: backendsecret
  backenddeploymentname: backend-deployment
  backendreplicas: 2
  backendpodselector: backend
  backendcontainername: backend
  backendimage:
    repository: doomerdpk/learnspherebackend
    tag: 6f5cd994b0585329599e23e2e62015ce7c704ac3
  backendsecretvolumename: env-file
  backendsecretmountpath: /app/secrets
  backendservicename: backend
frontend:
  frontendnamespace: frontendnamespace
  frontenddeploymentname: frontend-deployment
  frontendreplicas: 1
  frontendpodselector: frontend
  frontendcontainername: frontend
  frontendimage:
    repository: doomerdpk/learnspherefrontend
    tag: 204723f47f343d58efe87b004d210b11b60af46e
  frontendservicename: frontend
ingress:
  frontendingressname: frontendingress
  backendingressname: backendingress
  frontendingresshost: learnsphere.deepak.cfd
  backendingresshost: learnsphere-vercel.api.deepak.cfd
  frontendnamespace: frontendnamespace
  frontendservicename: frontend
  backendnamespace: backendnamespace
  backendservicename: backend
