db:
  pvcname: db-pvc
  pvstorage: 1Gi
  dbdeploymentname: db-deployment
  dbreplicas: 1
  dbpodselector: db
  dbcontainername: db
  dbimage:
    repository: mongo
    tag: "latest"
  dbvolumename: db-storage
  dbmountpath: /data/db
  dbservicename: db
backend:
  backendnamespace: backendnamespace
  backendconfigmapname: backendconfigmap
  backendsecretname: backendsecret
  backenddeploymentname: backend-deployment
  backendreplicas: 2
  backendpodselector: backend
  backendcontainername: backend
  backendimage:
    repository: doomerdpk/learnspherebackend
    tag: a19af5a2a0593762280c158a2a60eac6062b9924
  backendsecretvolumename: env-file
  backendsecretmountpath: /app/secrets
  backendservicename: backend
frontend:
  frontendnamespace: frontendnamespace
  frontenddeploymentname: frontend-deployment
  frontendreplicas: 1
  frontendpodselector: frontend
  frontendcontainername: frontend
  frontendimage:
    repository: doomerdpk/learnspherefrontend
    tag: a783fba8f7d6b2750d141950c92b99a20ee8b742
  frontendservicename: frontend
ingress:
  frontendingressname: frontendingress
  backendingressname: backendingress
  frontendingresshost: learnsphere.deepak.cfd
  backendingresshost: learnsphere-vercel.api.deepak.cfd
  frontendnamespace: frontendnamespace
  frontendservicename: frontend
  backendnamespace: backendnamespace
  backendservicename: backend
